// Explicit imports keep each grammar in its own lazy chunk. Historical names are kept below.
export const languageLoaders = {
  'accesslog': () => import('highlight.js/lib/languages/accesslog'),
  'apache': () => import('highlight.js/lib/languages/apache'),
  'arduino': () => import('highlight.js/lib/languages/arduino'),
  'asciidoc': () => import('highlight.js/lib/languages/asciidoc'),
  'awk': () => import('highlight.js/lib/languages/awk'),
  'bash': () => import('highlight.js/lib/languages/bash'),
  'basic': () => import('highlight.js/lib/languages/basic'),
  'c': () => import('highlight.js/lib/languages/c'),
  'clojure': () => import('highlight.js/lib/languages/clojure'),
  'clojure-repl': () => import('highlight.js/lib/languages/clojure-repl'),
  'cmake': () => import('highlight.js/lib/languages/cmake'),
  'coffeescript': () => import('highlight.js/lib/languages/coffeescript'),
  'cpp': () => import('highlight.js/lib/languages/cpp'),
  'csharp': () => import('highlight.js/lib/languages/csharp'),
  'css': () => import('highlight.js/lib/languages/css'),
  'dart': () => import('highlight.js/lib/languages/dart'),
  'diff': () => import('highlight.js/lib/languages/diff'),
  'django': () => import('highlight.js/lib/languages/django'),
  'dockerfile': () => import('highlight.js/lib/languages/dockerfile'),
  'dos': () => import('highlight.js/lib/languages/dos'),
  'elixir': () => import('highlight.js/lib/languages/elixir'),
  'elm': () => import('highlight.js/lib/languages/elm'),
  'erlang': () => import('highlight.js/lib/languages/erlang'),
  'excel': () => import('highlight.js/lib/languages/excel'),
  'go': () => import('highlight.js/lib/languages/go'),
  'gradle': () => import('highlight.js/lib/languages/gradle'),
  'graphql': () => import('highlight.js/lib/languages/graphql'),
  'groovy': () => import('highlight.js/lib/languages/groovy'),
  'haml': () => import('highlight.js/lib/languages/haml'),
  'handlebars': () => import('highlight.js/lib/languages/handlebars'),
  'haskell': () => import('highlight.js/lib/languages/haskell'),
  'http': () => import('highlight.js/lib/languages/http'),
  'ini': () => import('highlight.js/lib/languages/ini'),
  'java': () => import('highlight.js/lib/languages/java'),
  'javascript': () => import('highlight.js/lib/languages/javascript'),
  'json': () => import('highlight.js/lib/languages/json'),
  'kotlin': () => import('highlight.js/lib/languages/kotlin'),
  'latex': () => import('highlight.js/lib/languages/latex'),
  'less': () => import('highlight.js/lib/languages/less'),
  'llvm': () => import('highlight.js/lib/languages/llvm'),
  'lua': () => import('highlight.js/lib/languages/lua'),
  'makefile': () => import('highlight.js/lib/languages/makefile'),
  'markdown': () => import('highlight.js/lib/languages/markdown'),
  'matlab': () => import('highlight.js/lib/languages/matlab'),
  'nginx': () => import('highlight.js/lib/languages/nginx'),
  'objectivec': () => import('highlight.js/lib/languages/objectivec'),
  'perl': () => import('highlight.js/lib/languages/perl'),
  'php': () => import('highlight.js/lib/languages/php'),
  'php-template': () => import('highlight.js/lib/languages/php-template'),
  'plaintext': () => import('highlight.js/lib/languages/plaintext'),
  'powershell': () => import('highlight.js/lib/languages/powershell'),
  'python': () => import('highlight.js/lib/languages/python'),
  'python-repl': () => import('highlight.js/lib/languages/python-repl'),
  'r': () => import('highlight.js/lib/languages/r'),
  'ruby': () => import('highlight.js/lib/languages/ruby'),
  'rust': () => import('highlight.js/lib/languages/rust'),
  'scala': () => import('highlight.js/lib/languages/scala'),
  'scss': () => import('highlight.js/lib/languages/scss'),
  'shell': () => import('highlight.js/lib/languages/shell'),
  'sql': () => import('highlight.js/lib/languages/sql'),
  'swift': () => import('highlight.js/lib/languages/swift'),
  'typescript': () => import('highlight.js/lib/languages/typescript'),
  'vbnet': () => import('highlight.js/lib/languages/vbnet'),
  'wasm': () => import('highlight.js/lib/languages/wasm'),
  'xml': () => import('highlight.js/lib/languages/xml'),
  'yaml': () => import('highlight.js/lib/languages/yaml'),
};

export const languageAliases: Record<string, keyof typeof languageLoaders> = {
  'adoc': 'asciidoc',
  'apacheconf': 'apache',
  'atom': 'xml',
  'bat': 'dos',
  'batch': 'dos',
  'c#': 'csharp',
  'c++': 'cpp',
  'cc': 'cpp',
  'cjs': 'javascript',
  'clj': 'clojure',
  'cmake.in': 'cmake',
  'cmd': 'dos',
  'coffee': 'coffeescript',
  'console': 'shell',
  'cs': 'csharp',
  'cson': 'coffeescript',
  'cts': 'typescript',
  'cxx': 'cpp',
  'docker': 'dockerfile',
  'edn': 'clojure',
  'erl': 'erlang',
  'ex': 'elixir',
  'exs': 'elixir',
  'gemspec': 'ruby',
  'golang': 'go',
  'gql': 'graphql',
  'gyp': 'python',
  'h': 'c',
  'h++': 'cpp',
  'hbs': 'handlebars',
  'hh': 'cpp',
  'hpp': 'cpp',
  'hs': 'haskell',
  'html': 'xml',
  'html.handlebars': 'handlebars',
  'html.hbs': 'handlebars',
  'htmlbars': 'handlebars',
  'https': 'http',
  'hxx': 'cpp',
  'iced': 'coffeescript',
  'ino': 'arduino',
  'ipython': 'python',
  'irb': 'ruby',
  'jinja': 'django',
  'js': 'javascript',
  'json5': 'json',
  'jsonc': 'json',
  'jsp': 'java',
  'jsx': 'javascript',
  'kt': 'kotlin',
  'ktm': 'kotlin',
  'kts': 'kotlin',
  'ktx': 'kotlin',
  'mak': 'makefile',
  'make': 'makefile',
  'md': 'markdown',
  'mjs': 'javascript',
  'mk': 'makefile',
  'mkd': 'markdown',
  'mkdown': 'markdown',
  'mm': 'objectivec',
  'mts': 'typescript',
  'nginxconf': 'nginx',
  'obj-c': 'objectivec',
  'obj-c++': 'objectivec',
  'objc': 'objectivec',
  'objective-c++': 'objectivec',
  'patch': 'diff',
  'php3': 'php',
  'php4': 'php',
  'php5': 'php',
  'php6': 'php',
  'pl': 'perl',
  'plist': 'xml',
  'pluto': 'lua',
  'pm': 'perl',
  'podspec': 'ruby',
  'ps': 'powershell',
  'ps1': 'powershell',
  'pwsh': 'powershell',
  'py': 'python',
  'pycon': 'python-repl',
  'rb': 'ruby',
  'rs': 'rust',
  'rss': 'xml',
  'sh': 'bash',
  'shellsession': 'shell',
  'svg': 'xml',
  'tex': 'latex',
  'text': 'plaintext',
  'thor': 'ruby',
  'toml': 'ini',
  'ts': 'typescript',
  'tsx': 'typescript',
  'txt': 'plaintext',
  'vb': 'vbnet',
  'wsf': 'xml',
  'xhtml': 'xml',
  'xjb': 'xml',
  'xls': 'excel',
  'xlsx': 'excel',
  'xsd': 'xml',
  'xsl': 'xml',
  'yml': 'yaml',
  'zsh': 'bash',
};
